### ISSUE TITLE
/ISSUE_TEMPLATE[/name.md] and /PULL_REQUEST_TEMPLATE[/name.md]

### ISSUE THREAD

**Issue by westurner** [joelparkerhenderson/github_special_files_and_paths#1]
Default: /ISSUE_TEMPLATE.md

/ISSUE_TEMPLATE/<name>.md</name>

Default: /PULL_REQUEST_TEMPLATE.md

/PULL_REQUEST_TEMPLATE/<name>.md</name>

... https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/

**Comment by joelparkerhenderson** [comment]
Thanks! I'll add these now.

**Comment by westurner** [comment]
Thanks!
