### ISSUE TITLE
Supported markup syntaxes

### ISSUE THREAD

**Issue by westurner** [joelparkerhenderson/github_special_files_and_paths#2]
https://github.com/github/markup/blob/master/README.md#markups

> * [.markdown, .mdown, .mkdn, .md](http://daringfireball.net/projects/markdown/) -- `gem install commonmarker` (https://github.com/gjtorikian/commonmarker)
> * [.textile](https://www.promptworks.com/textile) -- `gem install RedCloth` (https://github.com/jgarber/redcloth)
> * [.rdoc](https://ruby.github.io/rdoc/) -- `gem install rdoc -v 3.6.1`
> * [.org](http://orgmode.org/) -- `gem install org-ruby` (https://github.com/wallyqs/org-ruby)
> * [.creole](http://wikicreole.org/) -- `gem install creole` (https://github.com/larsch/creole)
> * [.mediawiki, .wiki](http://www.mediawiki.org/wiki/Help:Formatting) -- `gem install wikicloth` (https://github.com/nricciar/wikicloth)
> * [.rst](http://docutils.sourceforge.net/rst.html) -- `pip install docutils`
> * [.asciidoc, .adoc, .asc](http://asciidoc.org/) -- `gem install asciidoctor` (http://asciidoctor.org)
> * [.pod](http://search.cpan.org/dist/perl/pod/perlpod.pod) -- `Pod::Simple::XHTML`
  comes with Perl >= 5.10. Lower versions should install Pod::Simple from CPAN.

**Comment by joelparkerhenderson** [comment]
Thanks! I'll add these now.

**Comment by westurner** [comment]
Thanks!
