### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by ItsNickBarry** [joelparkerhenderson/github_special_files_and_paths#4]
Github uses Jekyll for static site hosting, loading configuration directly from the repository.  Is Jekyll within the scope of this guide?

**Comment by joelparkerhenderson** [comment]
Yes please. Would you like to add information about any special files and paths that relate to Jekyll? 

If you know how to add them in a pull request, that's great. Or if you prefer to simply reply to this comment with what you want added, I'll add it.

**Comment by ItsNickBarry** [comment]
A list of Jekyll files and directories is available [here](https://jekyllrb.com/docs/structure/).

There are a lot of them.  I think I'll need to reorganize the existing layout so that Jekyll has its own section.  Let me know if you're not into that.  Otherwise, I'll submit a pull request in a day or two.

**Comment by ItsNickBarry** [comment]
I decided to just list the Jekyll files and directories without description, lest this repository become a Jekyll tutorial.
